env: "dev"

application:
  app: "merch-store"

public_server:
  enable: true
  endpoint: "0.0.0.0"
  port: 8080
  shutdown_timeout: 30

gateway:
  port: 8090
  endpoint: "0.0.0.0"

storage:
  postgres:
    hosts:
      - "${DB_HOST}"
    port: 5432
    database: "merch-store-grpc"
    username: "champ001"
    password: "${DB_PASSWORD}"
    ssl_mode: "disable"
    connection_attempts: 3
    pool:
      max_connections: 50
      min_connections: 10
      max_lifetime: 3600
      max_idle_time: 300
      health_check_period: 30

  redis:
    host: "${REDIS_HOST}"
    port: 6379
    db: 0
    connection_attempts: 3

jwt:
  secret_key: "${JWT_SECRET_KEY}"
  token_expiry: 86400
  